CREATE TABLE [dbo].[AggregateFeatures] (
    [id]                        INT          IDENTITY (1, 1) NOT NULL,
    [request_id]                INT          NOT NULL,
    [uri_extention]             VARCHAR (10) NOT NULL,
    [uri_contains_os_cmd]       BIT          NOT NULL,
    [uri_contains_invalidchars] BIT          NOT NULL,
    [uri_contains_javascript]   BIT          NOT NULL,
    [hdr_contains_invalidchars] BIT          NOT NULL,
    [hdr_contains_html]         BIT          NOT NULL,
    [qs_contains_invalidchars]  BIT          NOT NULL,
    [qs_contains_javascript]    BIT          NOT NULL,
    [qs_contains_html]          BIT          NOT NULL,
    [qs_contains_os]            BIT          NOT NULL,
    [qs_contains_pathing]       BIT          NOT NULL,
    [uri_sql_score]             INT          NULL,
    [hdr_sql_score]             INT          NULL,
    [qs_sql_score]              INT          NULL,
    [uri_ldap_score]            INT          NULL,
    [hdr_ldap_score]            INT          NULL,
    [qs_ldap_score]             INT          NULL,
    [uri_os_score]              INT          NULL,
    [hdr_os_score]              INT          NULL,
    [qs_os_score]               INT          NULL,
    [uri_ssi_score]             INT          NULL,
    [hdr_ssi_score]             INT          NULL,
    [qs_ssi_score]              INT          NULL,
    [uri_xss_score]             INT          NULL,
    [hdr_xss_score]             INT          NULL,
    [qs_xss_score]              INT          NULL,
    [uri_xpath_score]           INT          NULL,
    [hdr_xpath_score]           INT          NULL,
    [qs_xpath_score]            INT          NULL,
    CONSTRAINT [PK_AggregateFeatures] PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [FK_AggregateFeatures_Request] FOREIGN KEY ([request_id]) REFERENCES [dbo].[Request] ([id])
);

