CREATE TABLE [dbo].[Request_Header] (
    [id]                         INT           IDENTITY (1, 1) NOT NULL,
    [Request_id]                 INT           NOT NULL,
    [Header_Host]                VARCHAR (MAX) NULL,
    [Header_Connection]          VARCHAR (MAX) NULL,
    [Header_Accept]              VARCHAR (MAX) NULL,
    [Header_Accept-Charset]      VARCHAR (MAX) NULL,
    [Header_Accept-Encoding]     VARCHAR (MAX) NULL,
    [Header_Accept-Language]     VARCHAR (MAX) NULL,
    [Header_Date]                VARCHAR (MAX) NULL,
    [Header_If-Unmodified-Since] VARCHAR (MAX) NULL,
    [Header_Referer]             VARCHAR (MAX) NULL,
    [Header_User-Agent]          VARCHAR (MAX) NULL,
    [Header_UA-CPU]              VARCHAR (MAX) NULL,
    [Header_Via]                 VARCHAR (MAX) NULL,
    [Header_Transfer-Encoding]   VARCHAR (MAX) NULL,
    [Header_Warning]             VARCHAR (MAX) NULL,
    [Header_Cache-Control]       VARCHAR (MAX) NULL,
    [Header_Cookie2]             VARCHAR (MAX) NULL,
    [Header_ETag]                VARCHAR (MAX) NULL,
    [Header_If-Modified-Since]   VARCHAR (MAX) NULL,
    [Header_If-Match]            VARCHAR (MAX) NULL,
    [Header_If-None-Match]       VARCHAR (MAX) NULL,
    [Header_Pragma]              VARCHAR (MAX) NULL,
    [Header_Authorization]       VARCHAR (MAX) NULL,
    [Header_TE]                  VARCHAR (MAX) NULL,
    [Header_Cookie]              VARCHAR (MAX) NULL,
    [Header_If-Range]            VARCHAR (MAX) NULL,
    [Header_Trailer]             VARCHAR (MAX) NULL,
    [Header_X-Serial-Number]     VARCHAR (MAX) NULL,
    [Header_Max-Forwards]        VARCHAR (MAX) NULL,
    [Header_Expect]              VARCHAR (MAX) NULL,
    [Header_Range]               VARCHAR (MAX) NULL,
    [Header_Client-ip]           VARCHAR (MAX) NULL,
    [Header_From]                VARCHAR (MAX) NULL,
    [Header_X-Forwarded-For]     VARCHAR (MAX) NULL,
    [Header_UA-OS]               VARCHAR (MAX) NULL,
    [Header_UA-Color]            VARCHAR (MAX) NULL,
    [Header_MIME-Version]        VARCHAR (MAX) NULL,
    [Header_~~~~~]               VARCHAR (MAX) NULL,
    [Header_Proxy-Authorization] VARCHAR (MAX) NULL,
    [Header_UA-Pixels]           VARCHAR (MAX) NULL,
    [Header_Upgrade]             VARCHAR (MAX) NULL,
    [Header_----]                VARCHAR (MAX) NULL,
    [Header_UA-Disp]             VARCHAR (MAX) NULL,
    [Header_Content-Length]      VARCHAR (MAX) NULL,
    [Header_Content-Language]    VARCHAR (MAX) NULL,
    [Header_Content-Encoding]    VARCHAR (MAX) NULL,
    [Header_Content-Location]    VARCHAR (MAX) NULL,
    [Header_Content-MD5]         VARCHAR (MAX) NULL,
    [Header_Content-Type]        VARCHAR (MAX) NULL,
    [Header_Expires]             VARCHAR (MAX) NULL,
    [Header_Last-Modified]       VARCHAR (MAX) NULL,
    CONSTRAINT [PK_Request_Header] PRIMARY KEY CLUSTERED ([id] ASC),
    CONSTRAINT [FK_Request_Header_Request] FOREIGN KEY ([Request_id]) REFERENCES [dbo].[Request] ([id])
);

